<?php
    $reviews = array(
    array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla."),
        array("Reiewee"=>"Rakerista02923",
        "OverallReview"=>3.8,
        "Review"=>"Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem mollis aliquam ut porttitor leo. Dui faucibus in ornare quam viverra orci. Blandit libero volutpat sed cras. Et tortor at risus viverra adipiscing. Sed vulputate odio ut enim blandit volutpat maecenas volutpat. Id volutpat lacus laoreet non curabitur gravida. Quam pellentesque nec nam aliquam sem et tortor consequat id. Diam volutpat commodo sed egestas egestas fringilla phasellus faucibus. Amet nisl purus in mollis nunc sed id. Neque volutpat ac tincidunt vitae semper quis lectus. Natoque penatibus et magnis dis parturient montes. Orci porta non pulvinar neque laoreet. Nisl pretium fusce id velit ut. At erat pellentesque adipiscing commodo elit at. Proin libero nunc consequat interdum varius sit. Commodo sed egestas egestas fringilla.")
    );
    foreach ($reviews as $review) {
        echo (
                "<div class='review_card'>
                    <div>
                        <p class='reviwee'>".$review["Reiewee"]."</p>
                        <p class='overallreview'>Rating: ".$review["OverallReview"]."</p>
                    </div>
                    <p class='review'>".$review["Review"]."</p>
                </div>
            "
        );
    }
                
?>